// <auto-generated />
using System;
using Chronolibris.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chronolibris.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120171331_RenameAspNetIdentityTables")]
    partial class RenameAspNetIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chronolibris.Domain.Entities.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric")
                        .HasColumnName("average_rating");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("ISBN")
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsFragment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fragment");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<long?>("ParentBookId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_book_id");

                    b.Property<long?>("PublisherId")
                        .HasColumnType("bigint")
                        .HasColumnName("publisher_id");

                    b.Property<long>("RatingsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("ratings_count");

                    b.Property<long>("ReviewsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("reviews_count");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<long?>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_books_country_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_books_language_id");

                    b.HasIndex("PublisherId")
                        .HasDatabaseName("ix_books_publisher_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_books_series_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_books_tag_id");

                    b.ToTable("books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AverageRating = 0m,
                            CountryId = 1L,
                            CoverPath = "BuddismHistory/BuddismJapanGrig/MainFile.png",
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Монография является первой в отечественной литературе попыткой...",
                            FilePath = "BuddismHistory/BuddismJapanGrig/MainFile.epub",
                            IsAvailable = true,
                            IsFragment = false,
                            LanguageId = 2L,
                            PublisherId = 2L,
                            RatingsCount = 0L,
                            ReviewsCount = 0L,
                            Title = "Буддизм в Японии",
                            Year = 1993
                        },
                        new
                        {
                            Id = 2L,
                            AverageRating = 0m,
                            CountryId = 1L,
                            CoverPath = "EconomicHistory/StructureBrodel/MainFile.png",
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Это — второе крупное исследование Ф. Броделя...",
                            FilePath = "EconomicHistory/StructureBrodel/MainFile.epub",
                            IsAvailable = true,
                            IsFragment = false,
                            LanguageId = 2L,
                            PublisherId = 1L,
                            RatingsCount = 0L,
                            ReviewsCount = 0L,
                            Title = "Структуры повседневности: возможное и невозможное",
                            Year = 1986
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.BookContent", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("BookId", "ContentId")
                        .HasName("pk_books_contents");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_books_contents_content_id");

                    b.ToTable("books_contents", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1L,
                            ContentId = 1L,
                            Order = 1
                        },
                        new
                        {
                            BookId = 2L,
                            ContentId = 2L,
                            Order = 1
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Bookmark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mark");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookmarks");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_bookmarks_book_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookmarks_user_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Content", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original");

                    b.Property<bool>("IsTranslate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_translate");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<long?>("ParentContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_content_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_contents");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_contents_country_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_contents_language_id");

                    b.ToTable("contents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Монография является первой в отечественной литературе попыткой проследить процесс становления японского буддизма...",
                            IsOriginal = true,
                            IsTranslate = false,
                            LanguageId = 2L,
                            Position = 0,
                            Title = "Буддизм в Японии",
                            Year = 1993
                        },
                        new
                        {
                            Id = 2L,
                            CountryId = 5L,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Это — второе крупное исследование Ф. Броделя. Первое — «Средиземное море и мир Средиземноморья в эпоху Филиппа II»...",
                            IsOriginal = false,
                            IsTranslate = true,
                            LanguageId = 2L,
                            Position = 0,
                            Title = "Структуры повседневности: возможное и невозможное",
                            Year = 1979
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Россия"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "СССР"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Российская империя"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "США"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Франция"
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Английский"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Русский"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Французский"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Немецкий"
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Participation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long?>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<long>("PersonRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_role_id");

                    b.HasKey("Id")
                        .HasName("pk_participations");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_participations_book_id");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_participations_content_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_participations_person_id");

                    b.HasIndex("PersonRoleId")
                        .HasDatabaseName("ix_participations_person_role_id");

                    b.ToTable("participations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContentId = 1L,
                            PersonId = 1L,
                            PersonRoleId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ContentId = 2L,
                            PersonId = 2L,
                            PersonRoleId = 1L
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.ToTable("persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Советский и российский востоковед-японист, литературовед, переводчица...",
                            ImagePath = "none",
                            Name = "Татьяна Петровна Григорьева"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Французский историк, член Французской академии...",
                            ImagePath = "Brodel/MainFile.jpeg",
                            Name = "Фернан Поль Ахилл Бродель"
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.PersonRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_person_roles");

                    b.ToTable("person_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Автор"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Переводчик"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Редактор"
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Publisher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.ToTable("publishers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryId = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Name = "Прогресс"
                        },
                        new
                        {
                            Id = 2L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Name = "Восточная литература"
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AverageRating")
                        .HasColumnType("bigint")
                        .HasColumnName("average_rating");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DislikesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislikes_count");

                    b.Property<long>("LikesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("likes_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_reviews_book_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.ReviewsRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<short>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews_ratings");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_reviews_ratings_review_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_ratings_user_id");

                    b.ToTable("reviews_ratings", (string)null);
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Selection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_selections");

                    b.ToTable("selections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            IsActive = true,
                            Name = "Экономическая история"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            IsActive = true,
                            Name = "История культуры"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            IsActive = true,
                            Name = "История мира"
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Series", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("PublisherId")
                        .HasColumnType("bigint")
                        .HasColumnName("publisher_id");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("PublisherId")
                        .HasDatabaseName("ix_series_publisher_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Shelf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shelves");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_shelves_user_id");

                    b.ToTable("shelves", (string)null);
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("TagTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_type_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("TagTypeId")
                        .HasDatabaseName("ix_tags_tag_type_id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.TagType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag_types");

                    b.ToTable("tag_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Место"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Время"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Персоналия"
                        });
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Theme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentThemeId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_theme_id");

                    b.HasKey("Id")
                        .HasName("pk_themes");

                    b.HasIndex("ParentThemeId")
                        .HasDatabaseName("ix_themes_parent_theme_id");

                    b.ToTable("themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Отечественная история"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "История религии"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "История культуры"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Социально-экономическая история"
                        });
                });

            modelBuilder.Entity("Chronolibris.Infrastructure.Data.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_entered_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("books_selections", b =>
                {
                    b.Property<long>("BooksId")
                        .HasColumnType("bigint")
                        .HasColumnName("books_id");

                    b.Property<long>("SelectionsId")
                        .HasColumnType("bigint")
                        .HasColumnName("selections_id");

                    b.HasKey("BooksId", "SelectionsId")
                        .HasName("pk_books_selections");

                    b.HasIndex("SelectionsId")
                        .HasDatabaseName("ix_books_selections_selections_id");

                    b.ToTable("books_selections", (string)null);
                });

            modelBuilder.Entity("books_shelves", b =>
                {
                    b.Property<long>("BooksId")
                        .HasColumnType("bigint")
                        .HasColumnName("books_id");

                    b.Property<long>("ShelvesId")
                        .HasColumnType("bigint")
                        .HasColumnName("shelves_id");

                    b.HasKey("BooksId", "ShelvesId")
                        .HasName("pk_books_shelves");

                    b.HasIndex("ShelvesId")
                        .HasDatabaseName("ix_books_shelves_shelves_id");

                    b.ToTable("books_shelves", (string)null);
                });

            modelBuilder.Entity("contents_themes", b =>
                {
                    b.Property<long>("ContentsId")
                        .HasColumnType("bigint")
                        .HasColumnName("contents_id");

                    b.Property<long>("ThemesId")
                        .HasColumnType("bigint")
                        .HasColumnName("themes_id");

                    b.HasKey("ContentsId", "ThemesId")
                        .HasName("pk_contents_themes");

                    b.HasIndex("ThemesId")
                        .HasDatabaseName("ix_contents_themes_themes_id");

                    b.ToTable("contents_themes", (string)null);
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Book", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Country", "Country")
                        .WithMany("Books")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_countries_country_id");

                    b.HasOne("Chronolibris.Domain.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_languages_language_id");

                    b.HasOne("Chronolibris.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("fk_books_publishers_publisher_id");

                    b.HasOne("Chronolibris.Domain.Entities.Series", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesId")
                        .HasConstraintName("fk_books_series_series_id");

                    b.HasOne("Chronolibris.Domain.Entities.Tag", null)
                        .WithMany("Books")
                        .HasForeignKey("TagId")
                        .HasConstraintName("fk_books_tags_tag_id");

                    b.Navigation("Country");

                    b.Navigation("Language");

                    b.Navigation("Publisher");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.BookContent", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Book", "Book")
                        .WithMany("BookContents")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_contents_books_book_id");

                    b.HasOne("Chronolibris.Domain.Entities.Content", "Content")
                        .WithMany("BookContents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_contents_contents_content_id");

                    b.Navigation("Book");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Book", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_books_book_id");

                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_users_user_id");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Content", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Country", "Country")
                        .WithMany("Contents")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contents_countries_country_id");

                    b.HasOne("Chronolibris.Domain.Entities.Language", "Language")
                        .WithMany("Contents")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contents_languages_language_id");

                    b.Navigation("Country");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Participation", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Book", "Book")
                        .WithMany("Participations")
                        .HasForeignKey("BookId")
                        .HasConstraintName("fk_participations_books_book_id");

                    b.HasOne("Chronolibris.Domain.Entities.Content", "Content")
                        .WithMany("Participations")
                        .HasForeignKey("ContentId")
                        .HasConstraintName("fk_participations_contents_content_id");

                    b.HasOne("Chronolibris.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participations_persons_person_id");

                    b.HasOne("Chronolibris.Domain.Entities.PersonRole", "PersonRole")
                        .WithMany()
                        .HasForeignKey("PersonRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participations_person_roles_person_role_id");

                    b.Navigation("Book");

                    b.Navigation("Content");

                    b.Navigation("Person");

                    b.Navigation("PersonRole");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Review", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Book", null)
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_books_book_id");

                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_user_id");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.ReviewsRating", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Review", null)
                        .WithMany("ReviewsRatings")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_ratings_reviews_review_id");

                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_ratings_users_user_id");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Series", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Series")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_series_publishers_publisher_id");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Shelf", b =>
                {
                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shelves_users_user_id");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.TagType", "TagType")
                        .WithMany("Tags")
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_tag_types_tag_type_id");

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Theme", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Theme", "ParentTheme")
                        .WithMany()
                        .HasForeignKey("ParentThemeId")
                        .HasConstraintName("fk_themes_themes_parent_theme_id");

                    b.Navigation("ParentTheme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Chronolibris.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("books_selections", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_selections_books_books_id");

                    b.HasOne("Chronolibris.Domain.Entities.Selection", null)
                        .WithMany()
                        .HasForeignKey("SelectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_selections_selections_selections_id");
                });

            modelBuilder.Entity("books_shelves", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_shelves_books_books_id");

                    b.HasOne("Chronolibris.Domain.Entities.Shelf", null)
                        .WithMany()
                        .HasForeignKey("ShelvesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_shelves_shelves_shelves_id");
                });

            modelBuilder.Entity("contents_themes", b =>
                {
                    b.HasOne("Chronolibris.Domain.Entities.Content", null)
                        .WithMany()
                        .HasForeignKey("ContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contents_themes_contents_contents_id");

                    b.HasOne("Chronolibris.Domain.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contents_themes_themes_themes_id");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Book", b =>
                {
                    b.Navigation("BookContents");

                    b.Navigation("Bookmarks");

                    b.Navigation("Participations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Content", b =>
                {
                    b.Navigation("BookContents");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Country", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Language", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Review", b =>
                {
                    b.Navigation("ReviewsRatings");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Series", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Chronolibris.Domain.Entities.TagType", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
